services:

  rabbitmq:
    image: rabbitmq:4.2.5-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - "${VOLUME_PATH}/rabbitmq:/var/lib/rabbitmq"
      - "${VOLUME_PATH}/rabbitmq:/var/log/rabbitmq"
  postgres:
    image: postgres:18.3
    container_name: postgresql-18.3
    ports:
      - "5432:5432"
    volumes:
      - "${VOLUME_PATH}/postgresql:/var/lib/postgresql/18/docker"

    environment:
      - POSTGRES_PASSWORD=s8
      - POSTGRES_USER=s8
      - POSTGRES_DB=awesome_pizza
      - PG_DATA /var/lib/postgresql/18/docker

  awesome-pizza:
    container_name: awesome-pizza
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      POSTGRES_USER: s8
      POSTGRES_PASSWORD: s8
      POSTGRES_DB: awesome_pizza
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432